Shop-Dotnet.Web/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using Shop_Dotnet.BLL.Contract;
using Shop_Dotnet.BLL.Core;
using Shop_Dotnet.BLL.Dto.Company;
using Shop_Dotnet.BLL.Extensions;
using Shop_Dotnet.BLL.Models;
using Shop_Dotnet.DAL.Entities;
using Shop_Dotnet.Utility;
using Shop_Dotnet.Web.Areas.Admin.ViewModels;
using System.Data;
using System.Security.Claims;

namespace Shop_Dotnet.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;

        public CompanyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public async Task<IActionResult> Index()
        {
            CompanyVM companyVM = new();
            var companies = await _companyService.GetAll();

            if (companies?.Data != null)
            {
                companyVM.CompanyList = companies.Data;
            }

            return View(companyVM);
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            CompanyVM companyVM = new();

            if (id == null || id == 0)
            {
                return View(companyVM);
            }
            else
            {
                var company = await _companyService.GetById(id!.Value);

                if (company == null) return NotFound();

                companyVM.Company = new CompanyModel();
                companyVM.Company = company.Data!;
                

                return View(companyVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CompanyVM companyVM)
        {
            if (ModelState.IsValid)
            {
                ServiceResult serviceResult = new();

                var claimsIdentity = (ClaimsIdentity)User.Identity!;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)!.Value;

                //Create
                if (companyVM.Company.Id == null || companyVM.Company.Id == 0)
                {
                    var saveCompanyDto = companyVM.Company.GetSaveCompanyDtoFromCompanyModel();
                    saveCompanyDto.RequestUser = userId;

                    serviceResult = await _companyService.SaveCompany(saveCompanyDto);
                }
                //Update
                else
                {
                    var updateCompanyDto = companyVM.Company.GetUpdateCompanyDtoFromCompanyModel();
                    updateCompanyDto.RequestUser = userId;

                    serviceResult = await _companyService.UpdateCompany(updateCompanyDto);
                }

                if (serviceResult == null || !serviceResult.Success)
                {
                    TempData["error"] = "Failed to create company.";
                    return View(companyVM);
                }

                TempData["success"] = serviceResult.Message;

                return RedirectToAction("Index");
            }
            else
            {
                return View(companyVM);
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity!;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            var deleteCompanyDto = new DeleteCompanyDto
            {
                Id = id,
                RequestUser = userId
            };

            ServiceResult serviceResult = await _companyService.DeleteCompany(deleteCompanyDto);

            if (serviceResult == null || !serviceResult.Success)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            if (serviceResult == null || !serviceResult.Success)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            return Json(new { success = true, message = "Deleted successfully" });
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var companies = await _companyService.GetAll();

            JObject json = JObject.Parse(companies.ToJson());
            JToken data = json["Data"]!;

            string jsonResult = data.ToString(Formatting.None);

            string responseJson = $"{{ \"data\": {jsonResult} }}";

            if (companies?.Data != null)
            {
                return Content(responseJson, "application/json");
            }
            else
            {
                return Problem();
            }
        }
        #endregion
    }
}

Shop-Dotnet.Web/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using Shop_Dotnet.BLL.Contract;
using Shop_Dotnet.BLL.Extensions;
using Shop_Dotnet.BLL.Models;
using Shop_Dotnet.BLL.Services;
using Shop_Dotnet.DAL.Entities;
using Shop_Dotnet.Utility;
using Shop_Dotnet.Web.Areas.Admin.ViewModels;
using Shop_Dotnet.Web.Areas.Customer.ViewModels;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;

namespace Shop_Dotnet.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize]
    public class OrderController : Controller
	{
		private readonly IOrderHeaderService _orderHeaderService;
		private readonly IOrderDetailService _orderDetailService;

		[BindProperty]
		public OrderVM OrderVM { get; set; } = new();

		public OrderController(IOrderHeaderService orderHeaderService, IOrderDetailService orderDetailService)
		{
			_orderHeaderService = orderHeaderService;
			_orderDetailService = orderDetailService;
		}

		public IActionResult Index()
		{ 
			return View();
		}

        public async Task<IActionResult> Details(int orderId)
        {
			var orderResult = await _orderHeaderService.GetById(orderId);
			var order = (OrderHeaderModel)orderResult.Data!;

			var orderDetails = await _orderDetailService.GetAll();
			var orderDetailsList = (IEnumerable<OrderDetail>)orderDetails.Data!;

			OrderVM orderVM = new()
			{
				OrderHeader = order,
				OrderDetail = orderDetailsList.Where(x => x.OrderHeaderId == orderId).ToList()
            };

            return View(orderVM);
        }

		[HttpPost]
		[Authorize(Roles = StaticDetails.ROLE_ADMIN + "," + StaticDetails.ROLE_EMPLOYEE)]
        public async Task<IActionResult> UpdateOrdelDetail()
        {
            var orderResult = await _orderHeaderService.GetById(OrderVM.OrderHeader!.Id);
            var orderHeader = (OrderHeaderModel)orderResult.Data!;

			orderHeader.Name = OrderVM.OrderHeader.Name;
			orderHeader.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
			orderHeader.StreetAddress = OrderVM.OrderHeader.StreetAddress;
			orderHeader.City = OrderVM.OrderHeader.City;
			orderHeader.State = OrderVM.OrderHeader.State;
			orderHeader.PostalCode = OrderVM.OrderHeader.PostalCode;

			if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier)) 
			{
				orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
			}

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeader.Carrier = OrderVM.OrderHeader.TrackingNumber;
            }

            var orderHeaderToUpdate = await _orderHeaderService.UpdateOrderHeader(orderHeader);

			TempData["success"] = "Order details updated sucessfully.";

            return RedirectToAction(nameof(Details), new { orderId = orderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = StaticDetails.ROLE_ADMIN + "," + StaticDetails.ROLE_EMPLOYEE)]
        public async Task<IActionResult> StartProcessing()
        {
			var orderHeaderResult = await _orderHeaderService.UpdateStatus(OrderVM.OrderHeader!.Id, StaticDetails.StatusInProcess);

			if (!orderHeaderResult.Success)
			{
				TempData["error"] = "Order status failed to update.";
			}
			else 
			{
                TempData["success"] = "Order status changed to processing";
            }

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = StaticDetails.ROLE_ADMIN + "," + StaticDetails.ROLE_EMPLOYEE)]
        public async Task<IActionResult> ShipOrder()
        {
			var orderHeader = await _orderHeaderService.ShipOrder(OrderVM.OrderHeader!);

			if (!orderHeader.Success) 
			{
                TempData["error"] = "Order status failed to update.";
                return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader!.Id });
            }

            var orderHeaderResult = await _orderHeaderService.UpdateStatus(OrderVM.OrderHeader!.Id, StaticDetails.StatusShipped);

            if (!orderHeaderResult.Success)
            {
                TempData["error"] = "Order status failed to update.";
            }
            else
            {
                TempData["success"] = "Order set to shipment.";
            }

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = StaticDetails.ROLE_ADMIN + "," + StaticDetails.ROLE_EMPLOYEE)]
        public async Task<IActionResult> CancelOrder()
        {
            var orderHeader = await _orderHeaderService.GetById(OrderVM.OrderHeader!.Id);

            if (orderHeader == null || !orderHeader.Success)
            {
                TempData["error"] = "Failed to cancel order";

                return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
            }

			if (orderHeader.Data!.PaymentStatus == StaticDetails.PaymentStatusApproved)
			{
				var options = new RefundCreateOptions
				{
					Reason = RefundReasons.RequestedByCustomer,
					PaymentIntent = orderHeader.Data.PaymentIntentId,
				};

				var service = new RefundService();
				Refund refund = service.Create(options);

				await _orderHeaderService.UpdateStatus(OrderVM.OrderHeader.Id, StaticDetails.StatusCancelled, StaticDetails.StatusRefunded);
			}
			else 
			{
                await _orderHeaderService.UpdateStatus(OrderVM.OrderHeader.Id, StaticDetails.StatusCancelled, StaticDetails.StatusCancelled);
            }

            TempData["success"] = "Order cancelled succesfully";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

		[HttpPost]
		[ActionName("Details")]
		public async Task<IActionResult> Details_PAY_NOW() 
		{
            var orderHeader = await _orderHeaderService.GetById(OrderVM.OrderHeader!.Id);
            var orderDetail = await _orderDetailService.GetAll();
            List<OrderDetail> orderDetails = orderDetail.Data!;

            OrderVM.OrderHeader = orderHeader.Data!;
            OrderVM.OrderDetail = orderDetails.Where(x => x.OrderHeaderId == OrderVM.OrderHeader.Id).ToList();

            var domain = Request.Scheme + "://" + Request.Host.Value + "/";

            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?orderId={OrderVM.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.OrderDetail)
            {
                var sessionLineItem = new SessionLineItemOptions()
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product!.Title
                        }
                    },
                    Quantity = item.Count
                };

                options.LineItems.Add(sessionLineItem);
            }

            var service = new SessionService();
            Session session = service.Create(options);

            var r1 = await _orderHeaderService
                .UpdateStripePaymentId(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public async Task<IActionResult> PaymentConfirmation(int orderHeaderId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity!;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            var orderHeader = await _orderHeaderService.GetById(orderHeaderId);

            if (orderHeader == null || orderHeader.Data == null) return View(orderHeaderId);

            if (orderHeader!.Data!.PaymentStatus == StaticDetails.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(orderHeader.Data.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    await _orderHeaderService.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
                    await _orderHeaderService.UpdateStatus(orderHeaderId, orderHeader.Data!.OrderStatus, StaticDetails.PaymentStatusApproved);
                }
            }

            return View(orderHeaderId);
        }

        #region API Calls
        [HttpGet]
		public async Task<IActionResult> GetAll(string status)
		{
            var claimsIdentity = (ClaimsIdentity)User.Identity!;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            List<OrderHeaderModel> orders;

			if (User.IsInRole(StaticDetails.ROLE_ADMIN) || User.IsInRole(StaticDetails.ROLE_EMPLOYEE))
			{
				var orderHeadersResult = await _orderHeaderService.GetAll();
				orders = orderHeadersResult.Data!;
			}
			else
			{
				var orderHeadersResult = await _orderHeaderService.GetAllByApplicationUserId(userId);
				orders = orderHeadersResult.Data!;
            }

            switch (status)
			{
				case "pending":
					orders = orders.Where(x => x.PaymentStatus == StaticDetails.PaymentStatusDelayedPayment).ToList();
					break;
				case "inprocess":
					orders = orders.Where(x => x.OrderStatus == StaticDetails.StatusInProcess).ToList();
					break;
				case "completed":
					orders = orders.Where(x => x.OrderStatus == StaticDetails.StatusShipped).ToList();
					break;
				case "approved":
					orders = orders.Where(x => x.OrderStatus == StaticDetails.StatusApproved).ToList();
					break;

Shop-Dotnet.Web/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shop_Dotnet.BLL.Contract;
using Shop_Dotnet.BLL.Models;
using Shop_Dotnet.Utility;
using System.Security.Claims;

namespace Shop_Dotnet.Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartViewComponent(IShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        public async Task<IViewComponentResult> InvokeAsync() 
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity!;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(StaticDetails.SessionCart) == null) 
                {
                    List<ShoppingCartModel> shoppingCarts = _shoppingCartService.GetAllByUserId(claim.Value).GetAwaiter().GetResult().Data!;
                    HttpContext.Session.SetInt32(StaticDetails.SessionCart, shoppingCarts.Count());
                }

                return View(HttpContext.Session.GetInt32(StaticDetails.SessionCart));
            }
            else 
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

Shop-Dotnet.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shop_Dotnet.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-color navbar-expand-sm navbar-toggleable-sm border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Orders</a>
                        </li>
                        @if (User.IsInRole(StaticDetails.ROLE_ADMIN))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                </ul>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/44zwc61xeap8l88qvs5tgcrkxvqt0l7of0ddis8nls14jr9u/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shop-Dotnet.Web/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null) 
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');    
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}